export const carros = [
  {
    id: "x",
    brand: "Ford",
    model: "Ka 2010",
    year: 2010,
    fuel: 1,
    mileage: 1030,
    color: "vermelho",
    fipePrice: 40000,
    price: 38000,
    descripition: "descrição do carro",
    is_active: true,
    user: {
      id: "1976eed2-da25-48de-a674-524074487fd4",
      name: "Nome",
      email: "email@mail.com",

      profile_image: undefined,
      password: "abc123",
      cpf: "12345678901",
      phone: "131231654",
      birthDate: "1564616489",
      isSeller: true,
      description: "descircao",
    },
    images: [
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/02-images/cruze-sport6-rs-carros.jpg?imwidth=960",
    ],
  },
  {
    id: "abc",
    brand: "Wolkswagen",
    model: "Gold 2015",
    year: 2015,
    fuel: 1,
    mileage: 1000,
    color: "vermelho",
    fipePrice: 40000,
    price: 38000,
    descripition: "descrição do carro",
    is_active: true,
    user: {
      id: "3dfc347c-a75f-484a-8cf7-808f7b2fb58b",
      name: "Nome",
      email: "email@mail.com",

      profile_image: undefined,
      password: "abc123",
      cpf: "12345678901",
      phone: "131231654",
      birthDate: "1564616489",
      isSeller: true,
      description: "descircao",
    },
    images: [
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/02-images/cruze-sport6-rs-carros.jpg?imwidth=960",
    ],
  },
  {
    id: "abc",
    brand: "Hyundai",
    model: "Veloster 2020",
    year: 2020,
    fuel: 1,
    mileage: 1000,
    color: "vermelho",
    fipePrice: 40000,
    price: 38000,
    descripition: "descrição do carro",
    is_active: true,
    user: {
      id: "3dfc347c-a75f-484a-8cf7-808f7b2fb58b",
      name: "Nome",
      email: "email@mail.com",

      profile_image: undefined,
      password: "abc123",
      cpf: "12345678901",
      phone: "131231654",
      birthDate: "1564616489",
      isSeller: true,
      description: "descircao",
    },
    images: [
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/02-images/cruze-sport6-rs-carros.jpg?imwidth=960",
    ],
  },
  {
    id: "abc",
    brand: "Fiat",
    model: "Palio",
    year: 2018,
    fuel: 1,
    mileage: 1000,
    color: "verde",
    fipePrice: 40000,
    price: 38000,
    descripition: "descrição do carro",
    is_active: true,
    user: {
      id: "sbaisa",
      name: "Nome",
      email: "email@mail.com",

      profile_image: undefined,
      password: "abc123",
      cpf: "12345678901",
      phone: "131231654",
      birthDate: "1564616489",
      isSeller: true,
      description: "descircao",
    },
    images: [
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/02-images/cruze-sport6-rs-carros.jpg?imwidth=960",
    ],
  },
  {
    id: "abc",
    brand: "Honda",
    model: "Fit",
    year: 2019,
    fuel: 1,
    mileage: 1000,
    color: "azul",
    fipePrice: 40000,
    price: 38000,
    descripition: "descrição do carro",
    is_active: true,
    user: {
      id: "dsds",
      name: "Nome",
      email: "email@mail.com",

      profile_image: undefined,
      password: "abc123",
      cpf: "12345678901",
      phone: "131231654",
      birthDate: "1564616489",
      isSeller: true,
      description: "descircao",
    },
    images: [
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/02-images/cruze-sport6-rs-carros.jpg?imwidth=960",
    ],
  },
  {
    id: "abc",
    brand: "Chevrolet",
    model: "Corsa",
    year: 2021,
    fuel: 1,
    mileage: 1000,
    color: "vermelho",
    fipePrice: 40000,
    price: 38000,
    descripition: "descrição do carro",
    is_active: true,
    user: {
      id: "7af6364f-5785-4663-a099-a00db2dd49a9",
      name: "Nome",
      email: "email@mail.com",

      profile_image: undefined,
      password: "abc123",
      cpf: "12345678901",
      phone: "131231654",
      birthDate: "1564616489",
      isSeller: true,
      description: "descircao",
    },
    images: [
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/02-images/cruze-sport6-rs-carros.jpg?imwidth=960",
    ],
  },
];
